name: Yad2 Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests python-dotenv geopy

      - name: Create env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env

      - name: Run bot
        run: python main.py